verses = [
    "The king sent his lady on the thirteenth Yule day",
    "Three stalks o' merry corn",
    "Three maids a-merry dancing",
    "Three hinds a-merry hunting",
    "An Arabian baboon",
    "Three swans a-merry swimming",
    "Three ducks a-merry laying",
    "A bull that was brown",
    "Three goldspinks",
    "Three starlings",
    "A goose that was grey",
    "Three plovers",
    "Three partridges",
    "A pippin go aye",
    "Wha learns my carol and carries it away?"
]
